FRUITS = [
    "apple",
    "apricot",
    "avocado",
    "banana",
    "blackberry",
    "blueberry",
    "cantaloupe",
    "cherry",
    "coconut",
    "cranberry",
    "cucumber",
    "fig",
    "grape",
    "grapefruit",
    "kiwi",
    "lemon",
    "lime",
    "lychee",
    "mango",
    "melon",
    "nectarine",
    "orange",
    "papaya",
    "peach",
    "pear",
    "pineapple",
    "plum",
    "pomegranate",
    "raspberry",
    "strawberry",
    "tangerine",
    "watermelon",
]


# Do not contain fruits
FOOD = [
    "cake",
    "cheese",
    "chicken",
    "chocolate",
    "cookie",
    "crab",
    "curry",
    "donut",
    "egg",
    "fish",
    "flour",
    "french fries",
    "fries",
    "garlic",
    "biscuit",
    "bread",
    "meat",
    "noodles",
    "pasta",
    "pizza",
    "rice",
    "sausage",
    "soup",
    "spaghetti",
    "steak",
    "sushi",
    "taco",
    "tamale",
    "tortilla",
    "vegetable",
]

DRINKS = [ 
    "beer",
    "cider",
    "coffee",
    "cola",
    "juice",
    "milk",
    "orange juice",
    "soda",
    "tea",
    "water",
    "milk",
    "wine",
    "vodka",
    "whiskey",
    "rum",
    "gin",
    "tequila",
    "brandy",
    "champagne",
    "smoothie",
    "coca cola",
    "fanta",
    "sprite",
    "pepsi",
    "7up",
]

COLORS = [
    "red",
    "orange",
    "yellow",
    "green",
    "blue",
    "indigo",
    "violet",
    "black",
    "white",
    "gray",
    "brown",
    "pink",
    "purple",
    "magenta",
    "crimson",
    "coral",
    "blurple",
    "silver",
    "gold",
    "rainbow",
    "cyan",
    "lime",
    "olive",
    "maroon",
    "navy",
    "aqua",
    "teal",
    "torquoise",
    "lime green",
    "lavender",
    "fuchsia",
]

ANIMALS = [
    "alligator",
    "ant",
    "bear",
    "bee",
    "bird",
    "camel",
    "cat",
    "cheetah",
    "chicken",
    "chimpanzee",
    "cow",
    "crocodile",
    "deer",
    "dog",
    "dolphin",
    "duck",
    "eagle",
    "elephant",
    "fish",
    "fly",
    "fox",
    "frog",
    "giraffe",
    "goat",
    "goldfish",
    "hamster",
    "hippopotamus",
    "horse",    
    "kangaroo",
    "kitten",
    "lion",
    "lobster",
    "monkey",
    "octopus",
    "owl",
    "panda",
    "pig",
    "puppy",
    "rabbit",
    "rat",
    "scorpion",
    "seal",
    "shark",
    "sheep",
    "snail",
    "snake",
    "spider",
    "squirrel",
    "tiger",
    "turtle",
    "wolf",
    "gorilla",
    "donkey",
    "goat",
]

COUNTRY_DICT = {
    "afghanistan": "af",
    "albania": "al",
    "algeria": "dz",
    "andorra": "ad",
    "angola": "ao",
    "antigua and barbuda": "ag",
    "argentina": "ar",
    "armenia": "am",
    "australia": "au",
    "austria": "at",
    "azerbaijan": "az",
    "bahamas": "bs",
    "bahrain": "bh",
    "bangladesh": "bd",
    "barbados": "bb",
    "belarus": "by",
    "belgium": "be",
    "belize": "bz",
    "benin": "bj",
    "bhutan": "bt",
    "bolivia": "bo",
    "bosnia and herzegovina": "ba",
    "botswana": "bw",
    "brazil": "br",
    "brunei": "bn",
    "bulgaria": "bg",
    "burkina faso": "bf",
    "burundi": "bi",
    "cambodia": "kh",
    "cameroon": "cm",
    "canada": "ca",
    "cape verde": "cv",
    "central african republic": "cf",
    "chad": "td",
    "chile": "cl",
    "china": "cn",
    "colombia": "co",
    "comoros": "km",
    "congo": "cg",
    "costa rica": "cr",
    "cote d'ivoire": "ci",
    "croatia": "hr",
    "cuba": "cu",
    "cyprus": "cy",
    "czech republic": "cz",
    "denmark": "dk",
    "djibouti": "dj",
    "dominica": "dm",
    "dominican republic": "do",
    "ecuador": "ec",
    "egypt": "eg",
    "el salvador": "sv",
    "equatorial guinea": "gq",
    "eritrea": "er",
    "estonia": "ee",
    "ethiopia": "et",
    "fiji": "fj",
    "finland": "fi",
    "france": "fr",
    "gabon": "ga",
    "gambia": "gm",
    "georgia": "ge",
    "germany": "de",
    "ghana": "gh",
    "greece": "gr",
    "grenada": "gd",
    "guatemala": "gt",
    "guinea": "gn",
    "guinea-bissau": "gw",
    "guyana": "gy",
    "haiti": "ht",
    "honduras": "hn",
    "hungary": "hu",
    "iceland": "is",
    "india": "in",
    "indonesia": "id",
    "iran": "ir",
    "iraq": "iq",
    "ireland": "ie",
    "israel": "il",
    "italy": "it",
    "jamaica": "jm",
    "japan": "jp",
    "jordan": "jo",
    "kazakhstan": "kz",
    "kenya": "ke",
    "kiribati": "ki",
    "korea, north": "kp",
    "korea, south": "kr",
    "kosovo": "xk",
    "kuwait": "kw",
    "kyrgyzstan": "kg",
    "laos": "la",
    "latvia": "lv",
    "lebanon": "lb",
    "lesotho": "ls",
    "liberia": "lr",
    "libya": "ly",
    "liechtenstein": "li",
    "lithuania": "lt",
    "luxembourg": "lu",
    "macedonia": "mk",
    "madagascar": "mg",
    "malawi": "mw",
    "malaysia": "my",
    "maldives": "mv",
    "mali": "ml",
    "malta": "mt",
    "marshall islands": "mh",
    "mauritania": "mr",
    "mauritius": "mu",
    "mexico": "mx",
    "micronesia": "fm",
    "moldova": "md",
    "monaco": "mc",
    "mongolia": "mn",
    "montenegro": "me",
    "morocco": "ma",
    "mozambique": "mz",
    "myanmar": "mm",
    "namibia": "na",
    "nauru": "nr",
    "nepal": "np",
    "netherlands": "nl",
    "new zealand": "nz",
    "nicaragua": "ni",
    "niger": "ne",
    "nigeria": "ng",
    "norway": "no",
    "oman": "om",
    "pakistan": "pk",
    "palau": "pw",
    "panama": "pa",
    "papua new guinea": "pg",
    "paraguay": "py",
    "peru": "pe",
    "philippines": "ph",
    "poland": "pl",
    "portugal": "pt",
    "qatar": "qa",
    "romania": "ro",
    "russia": "ru",
    "rwanda": "rw",
    "st kitts and nevis": "kn",
    "st lucia": "lc",
    "saint vincent and the grenadines": "vc",
    "samoa": "ws",
    "san marino": "sm",
    "sao tome and principe": "st",
    "saudi arabia": "sa",
    "senegal": "sn",
    "serbia": "rs",
    "seychelles": "sc",
    "sierra leone": "sl",
    "singapore": "sg",
    "slovakia": "sk",
    "slovenia": "si",
    "solomon islands": "sb",
    "somalia": "so",
    "south africa": "za",
    "spain": "es",
    "sri lanka": "lk",
    "sudan": "sd",
    "suriname": "sr",
    "swaziland": "sz",
    "sweden": "se",
    "switzerland": "ch",
    "syria": "sy",
    "taiwan": "tw",
    "tajikistan": "tj",
    "tanzania": "tz",
    "thailand": "th",
    "togo": "tg",
    "tonga": "to",
    "trinidad and tobago": "tt",
    "tunisia": "tn",
    "turkey": "tr",
    "turkmenistan": "tm",
    "tuvalu": "tv",
    "uganda": "ug",
    "ukraine": "ua",
    "united arab emirates": "ae",
    "united kingdom": "gb",
    "united states": "us",
    "uruguay": "uy",
    "uzbekistan": "uz",
    "vanuatu": "vu",
    "venezuela": "ve",
    "vietnam": "vn",
    "yemen": "ye",
    "zambia": "zm",
    "zimbabwe": "zw"
}

COUNTRIES = list(COUNTRY_DICT.keys())

VEHICLES = [
    "car",
    "van",
    "truck",
    "bus",
    "motorcycle",
    "bicycle",
    "scooter",
    "moped",
    "tricycle",
    "tractor",
    "trailer",
    "skateboard",
]

LANGUAGES_DICT = {
    "afrikaans": "af",
    "akan": "ak",
    "albanian": "sq",
    "amharic": "am",
    "arabic": "ar",
    "armenian": "hy",
    "assamese": "as",
    "asu": "asa",
    "azerbaijani": "az",
    "bambara": "bm",
    "basque": "eu",
    "belarusian": "be",
    "bemba": "bem",
    "bena": "bez",
    "bengali": "bn",
    "bosnian": "bs",
    "bulgarian": "bg",
    "burmese": "my",
    "catalan": "ca",
    "cherokee": "chr",
    "chiga": "cgg",
    "chinese_simplified": "zh_cn",
    "chinese_traditional": "zh_tw",
    "cornish": "kw",
    "croatian": "hr",
    "czech": "cs",
    "danish": "da",
    "dutch": "nl",
    "dutch_vulgar": "nl_vulgar",
    "embu": "ebu",
    "english_vulgar": "en_vulgar",
    "esperanto": "eo",
    "estonian": "et",
    "ewe": "ee",
    "faroese": "fo",
    "filipino": "fil",
    "finnish": "fi",
    "french": "fr",
    "fulah": "ff",
    "galician": "gl",
    "ganda": "lg",
    "georgian": "ka",
    "german": "de",
    "greek": "el",
    "gujarati": "gu",
    "gusii": "guz",
    "hausa": "ha",
    "hawaiian": "haw",
    "hebrew": "he",
    "hindi": "hi",
    "hungarian": "hu",
    "icelandic": "is",
    "igbo": "ig",
    "indonesian": "id",
    "irish": "ga",
    "italian": "it",
    "japanese": "ja",
    "kabuverdianu": "kea",
    "kabyle": "kab",
    "kalaallisut": "kl",
    "kalenjin": "kln",
    "kamba": "kam",
    "kannada": "kn",
    "kazakh": "kk",
    "khmer": "km",
    "kikuyu": "ki",
    "kinyarwanda": "rw",
    "konkani": "kok",
    "korean": "ko",
    "langi": "lag",
    "latvian": "lv",
    "lithuanian": "lt",
    "luo": "luo",
    "luyia": "luy",
    "macedonian": "mk",
    "machame": "jmc",
    "makonde": "kde",
    "malagasy": "mg",
    "malay": "ms",
    "malayalam": "ml",
    "maltese": "mt",
    "manx": "gv",
    "marathi": "mr",
    "masai": "mas",
    "meru": "mer",
    "morisyen": "mfe",
    "nama": "naq",
    "nepali": "ne",
    "norwegian": "nb",
    "nyankole": "nyn",
    "oriya": "or",
    "oromo": "om",
    "pashto": "ps",
    "persian": "fa",
    "polish": "pl",
    "portuguese": "pt",
    "punjabi": "pa",
    "romanian": "ro",
    "romansh": "rm",
    "rombo": "rof",
    "russian": "ru",
    "rwa": "rwk",
    "samburu": "saq",
    "sango": "sg",
    "sena": "seh",
    "serbian": "sr",
    "shona": "sn",
    "sinhala": "si",
    "slovak": "sk",
    "slovenian": "sl",
    "soga": "xog",
    "somali": "so",
    "spanish": "es",
    "swahili": "sw",
    "swedish": "sv",
    "tachelhit": "shi",
    "taita": "dav",
    "tamil": "ta",
    "telugu": "te",
    "teso": "teo",
    "thai": "th",
    "tibetan": "bo",
    "tigrinya": "ti",
    "tonga": "to",
    "turkish": "tr",
    "ukrainian": "uk",
    "urdu": "ur",
    "uzbek": "uz",
    "vietnamese": "vi",
    "vunjo": "vun",
    "welsh": "cy",
    "yoruba": "yo",
    "zulu": "zu",
}

LANGUAGES = list(LANGUAGES_DICT.keys())

BUILDINGS = [
    "house",
    "apartment",
    "mall",
    "office",
    "hotel",
    "restaurant",
    "store",
    "school",
    "university",
    "hospital",
    "bank",
    "church",
    "mosque",
    "temple",
    "synagogue",
    "skyscraper",
    "warehouse",
    "cabin",
    "garage",
    "barn",
]